name       : gnome-screenshot
version    : 3.22.0
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-screenshot/3.22/gnome-screenshot-3.22.0.tar.xz : 8a05f14b3c7c6cb42f9848ad0332034c7fe5c34a69742910203588fd60b00230
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME Screenshot Utility
description: |
    Take screenshots with the GNOME Screenshot Utility
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %configure
build      : |
    %make
install    : |
    %make_install
