name        : gnome-screenshot
version     : 3.18.0
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-screenshot/3.18/gnome-screenshot-3.18.0.tar.xz : eba64dbf4acf0ab8222fec549d0a4f2dd7dbd51c255e7978dedf1f5c06a98841
license     :
    - GPLv2+
summary     : GNOME Screenshot Utility
builddeps   :
    - pkgconfig(xext)
    - pkgconfig(x11)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
description : |
    Take screenshots with the GNOME Screenshot Utility
setup      : |
    %patch -p1 <$pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %configure
build      : |
    %make
install    : |
    %make_install
