name       : gnome-screenshot
version    : 3.25.0
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-screenshot/3.25/gnome-screenshot-3.25.0.tar.xz : 0d560a4ac3fc74d20ca0d95c82269be7d2bb52258e6e1c5971a9362730292c71
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME Screenshot Utility
description: |
    Take screenshots with the GNOME Screenshot Utility
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
