name       : gnome-screenshot
version    : 3.26.0
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-screenshot/3.26/gnome-screenshot-3.26.0.tar.xz : 1bbc11595d3822f4b92319cdf9ba49dd00f5471b6046c590847dc424a874c8bb
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME Screenshot Utility
description: |
    Take screenshots with the GNOME Screenshot Utility
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
