name       : gnome-screenshot
version    : '41.0'
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-screenshot/41/gnome-screenshot-41.0.tar.xz : 4adb7dec926428f74263d5796673cf142e4720b6e768f5468a8d0933f98c9597
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Screenshot Utility
description: |
    Take screenshots with the GNOME Screenshot Utility
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libhandy-1)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
