name       : gnome-screenshot
version    : 3.32.0
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-screenshot/3.32/gnome-screenshot-3.32.0.tar.xz : 8b609f70083ebb95a754e9f11a18a67d2c2723080d672f2faebe54f9633b0a26
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Screenshot Utility
description: |
    Take screenshots with the GNOME Screenshot Utility
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
