name       : gnome-screenshot
version    : 3.20.1
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-screenshot/3.20/gnome-screenshot-3.20.1.tar.xz : 06a89b6887146cdbbeb64adf11bdae21acf22b0422337041c66eedb21ef7e143
license    :
    - GPLv2+
summary    : GNOME Screenshot Utility
builddeps  :
    - pkgconfig(xext)
    - pkgconfig(x11)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
description: |
    Take screenshots with the GNOME Screenshot Utility
setup      : |
    %patch -p1 <$pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %configure
build      : |
    %make
install    : |
    %make_install
