name       : gnome-screenshot
version    : 3.36.0
release    : 19
source     :
    - https://download.gnome.org/sources/gnome-screenshot/3.36/gnome-screenshot-3.36.0.tar.xz : 33495d892707179254b743f8f70c9a82cde5c5f2c7ea3db634a2ba7ea7331266
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Screenshot Utility
description: |
    Take screenshots with the GNOME Screenshot Utility
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
