name       : gnome-screenshot
version    : 3.34.0
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-screenshot/3.34/gnome-screenshot-3.34.0.tar.xz : c80af5f7a2bed4348585eb18dc4e60af5beba4f13d8ccf6ab1ee1d0912c2b1e6
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME Screenshot Utility
description: |
    Take screenshots with the GNOME Screenshot Utility
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-highly-buggy-fallback-flash.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
